### ISSUE TITLE
Piston CLI crash

### ISSUE THREAD

**Issue by ThreshMain** [engineer-man/piston#129]
Piston CLI crashes when supplied with code to run using a path that is not in the current directory
`cli/index.js run php 8.0.2 packages/php.test`

error from docker-composer 
```
piston_api_1      | /piston_api/src/executor/job.js:30
piston_api_1      |             throw new Error(`Main file "${this.main}" will not be written to disk`);
piston_api_1      |                   ^
piston_api_1      |
piston_api_1      | Error: Main file "packages/php.test" will not be written to disk
piston_api_1      |     at new Job (/piston_api/src/executor/job.js:30:19)
piston_api_1      |     at run_job (/piston_api/src/executor/routes.js:42:21)
piston_api_1      |     at Layer.handle [as handle_request] (/piston_api/node_modules/express/lib/router/layer.js:95:5)
piston_api_1      |     at next (/piston_api/node_modules/express/lib/router/route.js:137:13)
piston_api_1      |     at validate (/piston_api/src/index.js:83:9)
piston_api_1      |     at Layer.handle [as handle_request] (/piston_api/node_modules/express/lib/router/layer.js:95:5)
piston_api_1      |     at next (/piston_api/node_modules/express/lib/router/route.js:137:13)
piston_api_1      |     at middleware (/piston_api/node_modules/express-validator/src/middlewares/check.js:16:13)
piston_api_1      |     at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
error from the CLI
```
FetchError: request to http://127.0.0.1:6969/jobs failed, reason: socket hang up
    at ClientRequest.<anonymous> (/data1/GitHub/piston/cli/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketOnEnd (_http_client.js:493:9)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

**Comment by HexF** [comment]
Fixed with 2ab508b4d22a10b6f0b851c180ed9e899355a964
