### ISSUE TITLE
Error when trying to deploy Piston: "Error: Cannot find module 'fs/promises'"

### ISSUE THREAD

**Issue by mehmetron** [engineer-man/piston#303]
This is the error when I try to do anything with the cli like```cli/index.js ppman install node```
```bash
root@ubuntu:~/piston# cli/index.js ppman install node
/root/piston/cli/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/piston/cli/commands/ppman_commands/spec.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I can install and list packages just fine with the api but the cli is giving me this same error anytime I want to do something.

My deployment server is an Ubuntu 20.04.2 LTS

**Comment by HexF** [comment]
Update nodejs
https://joshtronic.com/2021/05/09/how-to-install-nodejs-16-on-ubuntu-2004-lts/

**Comment by HexF** [comment]
Also duplicate #292
